/**
 * All user-facing German texts. Wording comes verbatim from the design/prototype
 * (00-docs/15-design). Do not scatter strings across components.
 */
export const strings = {
  app: {
    name: 'Stadtfest-Finder',
    tagline:
      'Stadtfeste, Volksfeste, Kirmes und Weihnachtsmärkte in deiner Nähe.',
    comingSoon: 'Die Karte folgt in Kürze.',
  },
  common: {
    loading: 'Einen Moment …',
    retry: 'Erneut versuchen',
    close: 'Schließen',
    done: 'Fertig',
  },
  discover: {
    searchPlaceholder: 'Fest oder Ort suchen',
    clearSearch: 'Suche leeren',
    openFilter: 'Filter öffnen',
    activeFilters: (n: number) => `${n} aktive Filter`,
    profile: 'Profil',
    loadingEvents: 'Feste werden geladen …',
    loadFailed: 'Feste konnten nicht geladen werden',
    offline: (time: string) => `Offline · zuletzt geladen um ${time}`,
    zoomIn: 'Zoome hinein, um alle Feste zu sehen',
    attribution: '© MapTiler © OpenStreetMap-Mitwirkende',
    map: 'Karte',
    list: 'Liste',
    listHeader: (n: number) =>
      `${n} ${n === 1 ? 'Fest' : 'Feste'} im Kartenausschnitt`,
    listArea: (place: string) => `um ${place}`,
    changeArea: 'Ausschnitt ändern',
    jumpTo: (place: string) => `Zu ${place} springen`,
    sortedByDate: 'nach Datum',
    runningNow: 'Läuft gerade',
    stackTitle: (n: number) => `${n} Feste an diesem Ort`,
    selectedPin: (name: string, dateRange: string) =>
      `${name}, ${dateRange}. Erneut tippen öffnet die Details.`,
    photo: 'Foto',
    eventPhoto: 'Festfoto',
    distance: (km: number) =>
      `${km.toLocaleString('de-DE', {maximumFractionDigits: km < 10 ? 1 : 0})} km`,
    zoomInButton: 'Hineinzoomen',
    zoomOutButton: 'Herauszoomen',
    locate: 'Auf meinen Standort zentrieren',
    cluster: (n: number) => `${n} Feste, zum Vergrößern tippen`,
    emptyTitle: 'Keine Feste in diesem Kartenausschnitt',
    emptyText:
      'Hier gibt es mit diesen Filtern gerade nichts. Zoome heraus oder setze die Filter zurück.',
    zoomOut: 'Herauszoomen',
    resetFilters: 'Filter zurücksetzen',
    noResultsTitle: (q: string) => `Kein Fest für „${q}“`,
    noResultsText: 'Prüfe die Schreibweise oder suche nach einer Stadt.',
  },
  detail: {
    back: 'Zurück',
    share: 'Teilen',
    shareMessage: (name: string, period: string, url: string) =>
      `${name} · ${period}\n${url}`,
    favorite: 'Merken',
    distanceAway: (km: string) => `${km} entfernt`,
    period: 'Zeitraum',
    openingHours: 'Öffnungszeiten',
    price: 'Eintritt',
    about: 'Über das Fest',
    program: 'Programm & Highlights',
    place: 'Ort',
    directions: 'Anfahrt',
    transit: 'ÖPNV:',
    parking: 'Parken:',
    website: 'Offizielle Website',
    route: 'Route starten',
    invite: 'Einladen',
    cancelled: 'Abgesagt',
    cancelReason: (reason: string) => `Grund: ${reason}`,
    galleryCaption: (n: number, name: string) =>
      `Galerie · Foto ${n} · ${name}`,
    galleryCounter: (n: number, total: number) => `${n} / ${total}`,
    galleryPrevious: 'Vorheriges Bild',
    galleryNext: 'Nächstes Bild',
    openRoute: 'Route in der Karten-App öffnen',
    notFoundTitle: 'Dieses Fest ist nicht mehr verfügbar',
    notFoundText: 'Es wurde entfernt oder der Link ist nicht mehr gültig.',
    backToMap: 'Zur Karte',
    loadFailed: 'Das Fest konnte nicht geladen werden',
    mapsUnavailable: 'Keine Karten-App gefunden',
  },
  guestHint: {
    login: 'Anmelden oder registrieren',
    dismiss: 'Weiter ohne Konto',
    favorite: {
      title: 'Lieblingsfeste merken',
      text: 'Mit einem kostenlosen Konto speicherst du Favoriten auf deiner Zeitleiste und wirst vor Festbeginn erinnert.',
    },
    invite: {
      title: 'Freunde einladen',
      text: 'Mit einem Konto lädst du Freunde ein und siehst, wer zu- oder abgesagt hat.',
    },
  },
  login: {
    title: 'Willkommen',
    subtitle: 'Favoriten, Einladungen und Erinnerungen an einem Ort.',
    apple: 'Mit Apple fortfahren',
    google: 'Mit Google fortfahren',
    email: 'Mit E-Mail anmelden',
    register: 'Konto erstellen',
    legalPrefix: 'Mit der Anmeldung akzeptierst du die ',
    terms: 'Nutzungsbedingungen',
    legalMiddle: ' und die ',
    privacy: 'Datenschutzerklärung',
    legalSuffix: '.',
    failed: 'Anmeldung fehlgeschlagen · Bitte erneut versuchen',
    welcome: (firstName: string) =>
      firstName ? `Willkommen, ${firstName}!` : 'Willkommen!',
    favoriteSaved: 'Angemeldet · Fest gemerkt',
    sessionExpired: 'Bitte melde dich erneut an',
    loggedOut: 'Du bist abgemeldet',
  },
  favorites: {
    added: 'Zu Favoriten hinzugefügt',
    removed: 'Aus Favoriten entfernt',
    failed: 'Das hat nicht geklappt',
    add: (name: string) => `${name} merken`,
    remove: (name: string) => `${name} aus Favoriten entfernen`,
  },
  drawer: {
    guestTitle: 'Deine Festsaison auf einen Blick',
    guestText:
      'Mit einem kostenlosen Konto sammelst du Favoriten auf einer Zeitleiste, lädst Freunde ein und wirst vor Festbeginn erinnert.',
    guestLogin: 'Anmelden oder registrieren',
    guestHint: 'Alle Feste kannst du auch ohne Konto entdecken.',
    openAccount: 'Konto öffnen',
    logout: 'Abmelden',
    title: 'Deine Festsaison',
    upcoming: (n: number) =>
      n === 1 ? '1 Favorit steht an' : `${n} Favoriten stehen an`,
    showPast: (n: number) => `↑ Vergangene einblenden (${n})`,
    hidePast: '↓ Vergangene ausblenden',
    today: (day: string) => `HEUTE · ${day}`,
    past: 'vorbei',
    emptyTitle: 'Noch keine Favoriten',
    emptyText:
      'Tippe bei einem Fest auf das Herz. Es erscheint dann hier auf deiner Zeitleiste, sortiert nach Datum.',
    discover: 'Feste entdecken',
    loadFailed: 'Favoriten konnten nicht geladen werden',
    retry: 'Erneut versuchen',
    darkMode: 'Dunkelmodus',
    darkModeHint: 'Lange drücken: wieder wie das System',
    darkModeSystem: 'Darstellung folgt wieder dem System',
    moderator: 'Moderator-Ansicht',
  },
  mod: {
    images: {
      title: 'Bilder',
      add: '+ Hochladen',
      cover: 'Titelbild',
      coverTile: 'Titelbild',
      tile: (n: number) => `Bild ${n}`,
      remove: (n: number) => `Bild ${n} entfernen`,
      uploading: 'Lädt hoch',
      processing: 'Wird verarbeitet',
      failed: 'Fehlgeschlagen',
      retry: 'Erneut versuchen',
      longPressHint: 'Lange drücken für weitere Aktionen',
      rightsHint:
        'Nur Bilder hochladen, an denen du die Rechte hast. Keine erkennbaren Personen.',
      makeCover: 'Als Titelbild',
      removeImage: 'Bild entfernen',
      permissionDenied:
        'Ohne Zugriff auf deine Fotos kannst du keine Bilder hochladen. Du kannst ihn in den Einstellungen erlauben.',
      needsName:
        'Bitte gib zuerst einen Namen ein, dann kannst du Bilder hochladen.',
      draftCreated: 'Als Entwurf gespeichert, Bilder werden hochgeladen',
      uploadFailed: 'Das Bild konnte nicht hochgeladen werden.',
      tooMany: 'Ein Fest kann höchstens 12 Bilder haben.',
      coverSet: 'Titelbild geändert',
    },
    picker: {
      title: 'Ort auf der Karte wählen',
      hint: 'Karte verschieben und zoomen, der Pin bleibt in der Mitte.',
      confirm: 'Pin übernehmen',
    },
    banner: 'Moderator-Ansicht',
    bannerSubtitle: (region: string, name: string) =>
      name ? `Region ${region} · ${name}` : `Region ${region}`,
    exit: 'Beenden',
    exited: 'Zurück in der Nutzeransicht',
    forbidden: 'Die Moderator-Ansicht ist für dich nicht freigegeben',
    tabEvents: 'Feste',
    tabCategories: 'Kategorien',
    categoriesSoon: 'Die Kategorien-Verwaltung folgt in Kürze',
    title: 'Feste',
    newEvent: '+ Neues Fest',
    searchPlaceholder: 'Fest oder Ort in deiner Region',
    filterAll: 'Alle',
    status: {
      draft: 'Entwurf',
      published: 'Veröffentlicht',
      past: 'Vergangen',
      cancelled: 'Abgesagt',
    },
    autoFound: 'Automatisch gefunden',
    favorites: (n: number) => `♥ ${n}`,
    emptyTitle: 'Keine Feste gefunden',
    emptyText: 'Lege ein neues Fest an oder ändere die Suche.',
    loadFailed: 'Feste konnten nicht geladen werden',
    retry: 'Erneut versuchen',
    form: {
      newTitle: 'Neues Fest',
      statusLine: (status: string) => `Status: ${status}`,
      name: 'Name *',
      category: 'Kategorie *',
      period: 'Zeitraum *',
      start: 'Beginn',
      end: 'Ende',
      datePlaceholder: 'tt.mm.jjjj',
      openingHours: 'Öffnungszeiten',
      openingHoursPlaceholder: 'z. B. Sa 11–24 Uhr, So 11–19 Uhr',
      location: 'Ort *',
      locationAddress: 'Adresse',
      locationPin: 'Pin auf Karte',
      addressPlaceholder: 'Straße oder Platz, PLZ Ort',
      pinHint: 'Tippe, um den Pin auf der Karte zu setzen',
      pinEdit: 'Tippe, um den Pin zu verschieben',
      addressSearching: 'Suche Orte …',
      addressNoMatch: 'Kein Ort gefunden. Setze sonst einen Pin auf der Karte.',
      addressUnavailable:
        'Ortssuche gerade nicht erreichbar. Setze sonst einen Pin.',
      pinLabel: (lat: string, lon: string) => `${lat}, ${lon}`,
      description: 'Beschreibung',
      descriptionPlaceholder: 'Was erwartet die Besucher?',
      privacyHint: 'Keine personenbezogenen Daten eintragen.',
      program: 'Programm',
      programDay: 'Tag',
      programTime: 'Zeit',
      programTitle: 'Programmpunkt',
      programAdd: '+ Programmpunkt',
      programRemove: 'Programmpunkt entfernen',
      price: 'Eintritt',
      directions: 'Anfahrt',
      transitPlaceholder: 'ÖPNV',
      parkingPlaceholder: 'Parken',
      website: 'Website',
      saveDraft: 'Als Entwurf',
      publish: 'Veröffentlichen',
      publishChanges: 'Änderungen veröffentlichen',
      menu: 'Weitere Aktionen',
      cancelEvent: '⚠️ Fest absagen',
      deleteEvent: '🗑️ Fest löschen',
      menuClose: 'Abbrechen',
      back: 'Zurück',
    },
    toast: {
      draftSaved: 'Als Entwurf gespeichert',
      unpublished: 'Zurück auf Entwurf gesetzt · für Nutzer ausgeblendet',
      published: 'Veröffentlicht · jetzt in der App sichtbar',
      changesPublished: 'Änderungen veröffentlicht',
      cancelled: (n: number) =>
        n === 1
          ? 'Abgesagt · 1 Nutzer wird benachrichtigt'
          : `Abgesagt · ${n} Nutzer werden benachrichtigt`,
      deleted: 'Fest gelöscht',
      fixFields: 'Bitte fülle die markierten Pflichtfelder aus',
      failed: 'Speichern fehlgeschlagen · Bitte erneut versuchen',
    },
    conflict: {
      title: 'Dieses Fest wurde inzwischen geändert',
      text: 'Lade den aktuellen Stand neu. Deine Änderungen hier gehen dabei verloren.',
      reload: 'Neu laden',
    },
    cancelDialog: {
      title: 'Fest absagen?',
      text: (name: string, n: number) =>
        `„${name}“ wird als abgesagt markiert. ${n} Nutzer mit diesem Favoriten werden benachrichtigt.`,
      reasonPlaceholder: 'Grund (wird in der Benachrichtigung angezeigt)',
      confirm: 'Absagen und benachrichtigen',
    },
    deleteDialog: {
      title: 'Fest löschen?',
      text: (name: string) =>
        `„${name}“ wird endgültig entfernt. Das lässt sich nicht rückgängig machen.`,
      favoritesHint:
        'Nutzer mit diesem Favoriten werden nicht benachrichtigt; zum Informieren besser absagen.',
      confirm: 'Endgültig löschen',
    },
    cancel: 'Abbrechen',
    errors: {
      name: 'Bitte gib einen Namen ein.',
      category: 'Bitte wähle eine Kategorie.',
      start: 'Bitte wähle den Beginn.',
      end: 'Bitte wähle das Ende.',
      endBeforeStart: 'Das Ende liegt vor dem Beginn.',
      location: 'Bitte gib eine Adresse ein oder setze einen Pin.',
      region: 'Der Ort liegt außerhalb deiner Region.',
      website: 'Bitte gib eine gültige Web-Adresse ein.',
    },
  },
  name: {
    title: 'Wie heißt du?',
    text: 'Dein Name erscheint bei Einladungen und in gemeinsamen Listen.',
    firstName: 'Vorname',
    lastName: 'Nachname',
    save: 'Speichern',
    invalid: 'Bitte gib 1 bis 50 Zeichen ein.',
    saved: 'Name gespeichert',
    saveFailed: 'Speichern fehlgeschlagen · Bitte erneut versuchen',
  },
  account: {
    title: 'Konto',
    email: 'E-Mail-Adresse',
    emailHint: 'Die E-Mail-Adresse änderst du beim Anmeldedienst.',
    delete: 'Konto löschen',
    deleteTitle: 'Konto endgültig löschen?',
    deleteText:
      'Dein Konto, dein Name, deine Favoriten, Listen und Einladungen werden sofort gelöscht. Das lässt sich nicht rückgängig machen.',
    deleteConfirm: 'Endgültig löschen',
    cancel: 'Abbrechen',
    deleted: 'Dein Konto wurde gelöscht',
    deleteFailed: 'Löschen fehlgeschlagen · Bitte erneut versuchen',
  },
  filter: {
    title: 'Filter',
    time: 'Zeitraum',
    timeAll: 'Alle Termine',
    timeToday: 'Heute',
    timeWeekend: 'Dieses Wochenende',
    timeMonths: 'Zeitraum wählen',
    monthsHint: 'Monate wählen (mehrere möglich)',
    monthsChip: (n: number) => (n === 1 ? '1 Monat' : `${n} Monate`),
    category: 'Kategorie',
    reset: 'Zurücksetzen',
    apply: (n: number) => `${n} ${n === 1 ? 'Fest' : 'Feste'} anzeigen`,
    applyEmpty: 'Keine Treffer – trotzdem anwenden',
  },
} as const;
