/**
 * All user-facing German texts. Wording comes verbatim from the design/prototype
 * (00-docs/15-design). Do not scatter strings across components.
 */
export const strings = {
  app: {
    name: 'Stadtfest-Finder',
    tagline:
      'Stadtfeste, Volksfeste, Kirmes und Weihnachtsmärkte in deiner Nähe.',
    comingSoon: 'Die Karte folgt in Kürze.',
  },
  common: {
    loading: 'Einen Moment …',
    retry: 'Erneut versuchen',
    close: 'Schließen',
  },
  discover: {
    searchPlaceholder: 'Fest oder Ort suchen',
    clearSearch: 'Suche leeren',
    openFilter: 'Filter öffnen',
    activeFilters: (n: number) => `${n} aktive Filter`,
    profile: 'Profil',
    loadingEvents: 'Feste werden geladen …',
    loadFailed: 'Feste konnten nicht geladen werden',
    offline: (time: string) => `Offline · zuletzt geladen um ${time}`,
    zoomIn: 'Zoome hinein, um alle Feste zu sehen',
    attribution: '© MapTiler © OpenStreetMap-Mitwirkende',
    map: 'Karte',
    list: 'Liste',
    listHeader: (n: number) =>
      `${n} ${n === 1 ? 'Fest' : 'Feste'} im Kartenausschnitt`,
    listArea: (place: string) => `um ${place}`,
    changeArea: 'Ausschnitt ändern',
    jumpTo: (place: string) => `Zu ${place} springen`,
    sortedByDate: 'nach Datum',
    runningNow: 'Läuft gerade',
    photo: 'Foto',
    eventPhoto: 'Festfoto',
    distance: (km: number) =>
      `${km.toLocaleString('de-DE', {maximumFractionDigits: km < 10 ? 1 : 0})} km`,
    zoomInButton: 'Hineinzoomen',
    zoomOutButton: 'Herauszoomen',
    locate: 'Auf meinen Standort zentrieren',
    cluster: (n: number) => `${n} Feste, zum Vergrößern tippen`,
    emptyTitle: 'Keine Feste in diesem Kartenausschnitt',
    emptyText:
      'Hier gibt es mit diesen Filtern gerade nichts. Zoome heraus oder setze die Filter zurück.',
    zoomOut: 'Herauszoomen',
    resetFilters: 'Filter zurücksetzen',
    noResultsTitle: (q: string) => `Kein Fest für „${q}“`,
    noResultsText: 'Prüfe die Schreibweise oder suche nach einer Stadt.',
  },
  detail: {
    back: 'Zurück',
    share: 'Teilen',
    shareMessage: (name: string, period: string, url: string) =>
      `${name} · ${period}\n${url}`,
    favorite: 'Merken',
    distanceAway: (km: string) => `${km} entfernt`,
    period: 'Zeitraum',
    openingHours: 'Öffnungszeiten',
    price: 'Eintritt',
    about: 'Über das Fest',
    program: 'Programm & Highlights',
    place: 'Ort',
    directions: 'Anfahrt',
    transit: 'ÖPNV:',
    parking: 'Parken:',
    website: 'Offizielle Website',
    route: 'Route starten',
    invite: 'Einladen',
    cancelled: 'Abgesagt',
    cancelReason: (reason: string) => `Grund: ${reason}`,
    galleryCaption: (n: number, name: string) =>
      `Galerie · Foto ${n} · ${name}`,
    galleryCounter: (n: number, total: number) => `${n} / ${total}`,
    galleryPrevious: 'Vorheriges Bild',
    galleryNext: 'Nächstes Bild',
    openRoute: 'Route in der Karten-App öffnen',
    notFoundTitle: 'Dieses Fest ist nicht mehr verfügbar',
    notFoundText: 'Es wurde entfernt oder der Link ist nicht mehr gültig.',
    backToMap: 'Zur Karte',
    loadFailed: 'Das Fest konnte nicht geladen werden',
    mapsUnavailable: 'Keine Karten-App gefunden',
  },
  guestHint: {
    login: 'Anmelden oder registrieren',
    dismiss: 'Weiter ohne Konto',
    favorite: {
      title: 'Lieblingsfeste merken',
      text: 'Mit einem kostenlosen Konto speicherst du Favoriten auf deiner Zeitleiste und wirst vor Festbeginn erinnert.',
    },
    invite: {
      title: 'Freunde einladen',
      text: 'Mit einem Konto lädst du Freunde ein und siehst, wer zu- oder abgesagt hat.',
    },
  },
  login: {
    title: 'Willkommen',
    subtitle: 'Favoriten, Einladungen und Erinnerungen an einem Ort.',
    apple: 'Mit Apple fortfahren',
    google: 'Mit Google fortfahren',
    email: 'Mit E-Mail anmelden',
    register: 'Konto erstellen',
    legalPrefix: 'Mit der Anmeldung akzeptierst du die ',
    terms: 'Nutzungsbedingungen',
    legalMiddle: ' und die ',
    privacy: 'Datenschutzerklärung',
    legalSuffix: '.',
    failed: 'Anmeldung fehlgeschlagen · Bitte erneut versuchen',
    welcome: (firstName: string) =>
      firstName ? `Willkommen, ${firstName}!` : 'Willkommen!',
    favoriteSaved: 'Angemeldet · Fest gemerkt',
    sessionExpired: 'Bitte melde dich erneut an',
    loggedOut: 'Du bist abgemeldet',
  },
  favorites: {
    added: 'Zu Favoriten hinzugefügt',
    removed: 'Aus Favoriten entfernt',
    failed: 'Das hat nicht geklappt',
    add: (name: string) => `${name} merken`,
    remove: (name: string) => `${name} aus Favoriten entfernen`,
  },
  drawer: {
    guestTitle: 'Deine Festsaison auf einen Blick',
    guestText:
      'Mit einem kostenlosen Konto sammelst du Favoriten auf einer Zeitleiste, lädst Freunde ein und wirst vor Festbeginn erinnert.',
    guestLogin: 'Anmelden oder registrieren',
    guestHint: 'Alle Feste kannst du auch ohne Konto entdecken.',
    openAccount: 'Konto öffnen',
    logout: 'Abmelden',
    title: 'Deine Festsaison',
    upcoming: (n: number) =>
      n === 1 ? '1 Favorit steht an' : `${n} Favoriten stehen an`,
    showPast: (n: number) => `↑ Vergangene einblenden (${n})`,
    hidePast: '↓ Vergangene ausblenden',
    today: (day: string) => `HEUTE · ${day}`,
    past: 'vorbei',
    emptyTitle: 'Noch keine Favoriten',
    emptyText:
      'Tippe bei einem Fest auf das Herz. Es erscheint dann hier auf deiner Zeitleiste, sortiert nach Datum.',
    discover: 'Feste entdecken',
    loadFailed: 'Favoriten konnten nicht geladen werden',
    retry: 'Erneut versuchen',
    darkMode: 'Dunkelmodus',
    darkModeHint: 'Lange drücken: wieder wie das System',
    darkModeSystem: 'Darstellung folgt wieder dem System',
    moderator: 'Moderator-Ansicht',
    moderatorSoon: 'Die Moderator-Ansicht folgt in Kürze',
  },
  name: {
    title: 'Wie heißt du?',
    text: 'Dein Name erscheint bei Einladungen und in gemeinsamen Listen.',
    firstName: 'Vorname',
    lastName: 'Nachname',
    save: 'Speichern',
    invalid: 'Bitte gib 1 bis 50 Zeichen ein.',
    saved: 'Name gespeichert',
    saveFailed: 'Speichern fehlgeschlagen · Bitte erneut versuchen',
  },
  account: {
    title: 'Konto',
    email: 'E-Mail-Adresse',
    emailHint: 'Die E-Mail-Adresse änderst du beim Anmeldedienst.',
    delete: 'Konto löschen',
    deleteTitle: 'Konto endgültig löschen?',
    deleteText:
      'Dein Konto, dein Name, deine Favoriten, Listen und Einladungen werden sofort gelöscht. Das lässt sich nicht rückgängig machen.',
    deleteConfirm: 'Endgültig löschen',
    cancel: 'Abbrechen',
    deleted: 'Dein Konto wurde gelöscht',
    deleteFailed: 'Löschen fehlgeschlagen · Bitte erneut versuchen',
  },
  filter: {
    title: 'Filter',
    time: 'Zeitraum',
    timeAll: 'Alle Termine',
    timeToday: 'Heute',
    timeWeekend: 'Dieses Wochenende',
    timeMonths: 'Zeitraum wählen',
    monthsHint: 'Monate wählen (mehrere möglich)',
    monthsChip: (n: number) => (n === 1 ? '1 Monat' : `${n} Monate`),
    category: 'Kategorie',
    reset: 'Zurücksetzen',
    apply: (n: number) => `${n} ${n === 1 ? 'Fest' : 'Feste'} anzeigen`,
    applyEmpty: 'Keine Treffer – trotzdem anwenden',
  },
} as const;
