"""Synthetic seed data for the public catalog (categories, regions, events).

All events are fictional. Dates are offsets relative to "today" so that the data never
goes stale: e.g. `start=-3, days=10` is an event that started three days ago and runs for
ten days. IDs are deterministic (uuid5) so reseeding keeps deep links stable.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from uuid import NAMESPACE_URL, UUID, uuid5


def seed_id(kind: str, key: str) -> UUID:
    """Deterministic ID for a seed entity."""
    return uuid5(NAMESPACE_URL, f"https://stadtfest-finder.de/seed/{kind}/{key}")


@dataclass(frozen=True)
class SeedCategory:
    key: str
    name: str
    emoji: str
    color: str
    active: bool = True


@dataclass(frozen=True)
class SeedRegion:
    key: str
    name: str
    postal_codes: tuple[str, ...]


@dataclass(frozen=True)
class SeedProgramItem:
    day: int  # offset from the event start
    time_label: str
    title: str
    subtitle: str | None = None


@dataclass(frozen=True)
class SeedEvent:
    key: str
    name: str
    short_name: str
    category: str | None
    region: str
    status: str  # draft | published | cancelled
    start: int | None  # offset from today
    days: int  # duration in days (1 = one-day event)
    place: str
    address: str
    city: str
    postal_code: str
    lat: float | None
    lon: float | None
    opening_hours: tuple[str, ...] = ()
    price: str | None = None
    description: str | None = None
    transit: str | None = None
    parking: str | None = None
    website_url: str | None = None
    cancel_reason: str | None = None
    source: str = "manual"
    source_url: str | None = None
    program: tuple[SeedProgramItem, ...] = field(default_factory=tuple)


CATEGORIES = (
    SeedCategory("stadtfest", "Stadtfest", "🎪", "#FFB547"),
    SeedCategory("volksfest", "Volksfest & Kirmes", "🎡", "#FF6B8B"),
    SeedCategory("weihnachtsmarkt", "Weihnachtsmarkt", "🎄", "#5EEAD4"),
    SeedCategory("markt", "Markt & Messe", "🏰", "#8B9CFF"),
    SeedCategory("weinfest", "Weinfest", "🍷", "#C792EA", active=False),
)

REGIONS = (
    SeedRegion(
        "ostalb",
        "Ostalb",
        (
            "73430",
            "73431",
            "73432",
            "73433",
            "73434",
            "73441",
            "73447",
            "73450",
            "73453",
            "73457",
            "73460",
            "73463",
            "73466",
            "73467",
            "73469",
            "73479",
            "73485",
            "73486",
            "73488",
            "73489",
            "73491",
            "73492",
            "73494",
            "73495",
            "73497",
            "73499",
            "73525",
            "73527",
            "73529",
            "73540",
            "73547",
            "73550",
            "73553",
            "73557",
            "73560",
            "73563",
            "73565",
            "73566",
            "73568",
            "73569",
            "73571",
            "73572",
            "73574",
            "73575",
            "73577",
            "73579",
        ),
    ),
    SeedRegion("ulm", "Ulm und Alb-Donau", ("89073", "89075", "89077", "89079", "89081")),
    SeedRegion("heidenheim", "Heidenheim", ("89518", "89520", "89522", "89537", "89542")),
    SeedRegion("franken", "Franken", ("90402", "90403", "91541", "91550", "97070", "97072")),
    SeedRegion("stuttgart", "Stuttgart", ("70173", "70174", "70178", "73033", "74072")),
    SeedRegion("schwaben", "Bayerisch-Schwaben", ("86150", "86152", "86720", "80331")),
)

_P = SeedProgramItem

EVENTS = (
    # --- Ostalb: running, soon, later ---------------------------------------------------
    SeedEvent(
        "reichsstaedter-tage",
        "Reichsstädter Tage",
        "Reichsstädter",
        "stadtfest",
        "ostalb",
        "published",
        -3,
        12,
        "Marktplatz",
        "Marktplatz 1",
        "Aalen",
        "73430",
        48.8368,
        10.0932,
        opening_hours=("Mo-Do 11-23 Uhr", "Fr-Sa 11-1 Uhr", "So 11-22 Uhr"),
        price="Frei · Fahrgeschäfte kostenpflichtig",
        description="Das große Stadtfest in der Altstadt mit Umzug, Live-Musik auf drei Bühnen "
        "und Handwerkermarkt.",
        transit="Bahnhof Aalen, 5 Minuten zu Fuß",
        parking="Parkhaus Stadtmitte, Parkplatz Stadthalle",
        website_url="https://example.org/reichsstaedter-tage",
        program=(
            _P(0, "18:00 Uhr", "Eröffnung mit Fassanstich", "Marktplatz"),
            _P(1, "10:45 Uhr", "Historischer Umzug", "Start am Bahnhof"),
            _P(2, "20:00 Uhr", "Coverband-Nacht", "Bühne Rathaus"),
            _P(4, "11:00 Uhr", "Kinderprogramm", "Spritzenhausplatz"),
        ),
    ),
    SeedEvent(
        "wasseralfinger-kirbe",
        "Wasseralfinger Kirbe",
        "Kirbe",
        "volksfest",
        "ostalb",
        "published",
        8,
        4,
        "Festplatz Wasseralfingen",
        "Karlstraße 20",
        "Aalen",
        "73433",
        48.8631,
        10.1050,
        opening_hours=("Täglich 14-23 Uhr",),
        price="Frei",
        description="Traditionelle Kirbe mit Autoscooter, Kettenkarussell und Festzelt.",
    ),
    SeedEvent(
        "gmuender-stadtfest",
        "Gmünder Stadtfest",
        "Gmünder Fest",
        "stadtfest",
        "ostalb",
        "published",
        -1,
        3,
        "Johannisplatz",
        "Johannisplatz 3",
        "Schwäbisch Gmünd",
        "73525",
        48.7999,
        9.7980,
        opening_hours=("Fr 17-24 Uhr", "Sa 11-24 Uhr", "So 11-20 Uhr"),
        price="Frei",
        description="Stadtfest rund um das Münster mit Streetfood und Musik.",
        transit="Bahnhof Schwäbisch Gmünd, 8 Minuten zu Fuß",
    ),
    SeedEvent(
        "ellwanger-kalter-markt",
        "Kalter Markt",
        "Kalter Markt",
        "markt",
        "ostalb",
        "published",
        12,
        3,
        "Innenstadt",
        "Marktplatz 1",
        "Ellwangen (Jagst)",
        "73479",
        48.9617,
        10.1310,
        opening_hours=("Täglich 9-18 Uhr",),
        price="Frei",
        description="Pferdemarkt und Krämermarkt mit langer Tradition.",
    ),
    SeedEvent(
        "bopfinger-ipfmess",
        "Ipfmess",
        "Ipfmess",
        "volksfest",
        "ostalb",
        "published",
        20,
        5,
        "Festwiese",
        "Ipfstraße 12",
        "Bopfingen",
        "73441",
        48.8567,
        10.3528,
        opening_hours=("Täglich ab 14 Uhr",),
        price="Frei",
    ),
    SeedEvent(
        "heubacher-miederfest",
        "Heubacher Stadtfest",
        "Heubach",
        "stadtfest",
        "ostalb",
        "published",
        35,
        2,
        "Schlosshof",
        "Hauptstraße 53",
        "Heubach",
        "73540",
        48.7928,
        9.9336,
    ),
    SeedEvent(
        "oberkochener-herbstmarkt",
        "Herbstmarkt Oberkochen",
        "Herbstmarkt",
        "markt",
        "ostalb",
        "published",
        4,
        1,
        "Bürgerplatz",
        "Aalener Straße 2",
        "Oberkochen",
        "73447",
        48.7836,
        10.1050,
        opening_hours=("10-17 Uhr",),
        price="Frei",
    ),
    SeedEvent(
        "neresheimer-klosterfest",
        "Klosterfest Neresheim",
        "Klosterfest",
        "stadtfest",
        "ostalb",
        "cancelled",
        6,
        2,
        "Abtei Neresheim",
        "Abteistraße 1",
        "Neresheim",
        "73450",
        48.7542,
        10.3347,
        cancel_reason="Wegen Bauarbeiten am Klosterhof abgesagt.",
    ),
    SeedEvent(
        "aalener-weihnachtsmarkt",
        "Aalener Weihnachtsmarkt",
        "Weihnachtsmarkt",
        "weihnachtsmarkt",
        "ostalb",
        "published",
        60,
        26,
        "Marktplatz",
        "Marktplatz 1",
        "Aalen",
        "73430",
        48.8370,
        10.0935,
        opening_hours=("So-Do 11-20 Uhr", "Fr-Sa 11-21 Uhr"),
        price="Frei",
        description="Weihnachtsmarkt mit Krippe, Glühwein und Kinderkarussell.",
    ),
    SeedEvent(
        "gmuender-weihnachtsmarkt",
        "Gmünder Weihnachtsmarkt",
        "Weihnachtsmarkt",
        "weihnachtsmarkt",
        "ostalb",
        "published",
        62,
        24,
        "Marktplatz",
        "Marktplatz 1",
        "Schwäbisch Gmünd",
        "73525",
        48.7996,
        9.7985,
    ),
    SeedEvent(
        "ellwanger-adventsmarkt",
        "Ellwanger Adventsmarkt",
        "Adventsmarkt",
        "weihnachtsmarkt",
        "ostalb",
        "published",
        70,
        3,
        "Schlosshof",
        "Schloss ob Ellwangen",
        "Ellwangen (Jagst)",
        "73479",
        48.9587,
        10.1236,
    ),
    SeedEvent(
        "lorcher-klostermarkt",
        "Lorcher Klostermarkt",
        "Klostermarkt",
        "markt",
        "ostalb",
        "published",
        15,
        2,
        "Kloster Lorch",
        "Klosterweg 1",
        "Lorch",
        "73547",
        48.7970,
        9.6917,
    ),
    SeedEvent(
        "moegglinger-dorffest",
        "Dorffest Mögglingen",
        "Dorffest",
        "stadtfest",
        "ostalb",
        "published",
        2,
        2,
        "Rathausplatz",
        "Hauptstraße 30",
        "Mögglingen",
        "73563",
        48.8231,
        9.9583,
    ),
    SeedEvent(
        "abtsgmuender-kirchweih",
        "Kirchweih Abtsgmünd",
        "Kirchweih",
        "volksfest",
        "ostalb",
        "published",
        27,
        3,
        "Festplatz",
        "Kochertalstraße 5",
        "Abtsgmünd",
        "73453",
        48.8958,
        10.0017,
    ),
    # --- Ostalb: past, drafts, AI finds ---------------------------------------------------
    SeedEvent(
        "aalener-fruehlingsfest",
        "Aalener Frühlingsfest",
        "Frühlingsfest",
        "volksfest",
        "ostalb",
        "published",
        -150,
        10,
        "Greutplatz",
        "Greutweg 1",
        "Aalen",
        "73430",
        48.8410,
        10.0860,
    ),
    SeedEvent(
        "gmuender-sommerfest",
        "Sommerfest am Remspark",
        "Sommerfest",
        "stadtfest",
        "ostalb",
        "published",
        -40,
        3,
        "Remspark",
        "Remsparkweg 1",
        "Schwäbisch Gmünd",
        "73525",
        48.8012,
        9.7920,
    ),
    SeedEvent(
        "wasseralfinger-weinfest",
        "Weinfest am Stollen",
        "Weinfest",
        "weinfest",
        "ostalb",
        "published",
        18,
        3,
        "Besucherbergwerk",
        "Erzhäusle 1",
        "Aalen",
        "73433",
        48.8690,
        10.1170,
        description="Weinfest der Kategorie „Weinfest“ (deaktiviert): bleibt sichtbar, "
        "hat aber keinen Chip.",
    ),
    SeedEvent(
        "oberkochener-lichterfest",
        "Lichterfest Oberkochen",
        "Lichterfest",
        None,
        "ostalb",
        "draft",
        None,
        1,
        "",
        "",
        "Oberkochen",
        "73447",
        None,
        None,
    ),
    SeedEvent(
        "unterkochener-kirbe",
        "Unterkochener Kirbe",
        "Kirbe",
        "volksfest",
        "ostalb",
        "draft",
        30,
        3,
        "Festplatz Unterkochen",
        "Waldhäuser Straße 1",
        "Aalen",
        "73432",
        48.8176,
        10.1273,
        source="ai",
        source_url="https://example.org/unterkochen/kirbe",
    ),
    SeedEvent(
        "huettlinger-markt",
        "Hüttlinger Martinimarkt",
        "Martinimarkt",
        None,
        "ostalb",
        "draft",
        45,
        1,
        "Ortsmitte",
        "",
        "Hüttlingen",
        "73460",
        None,
        None,
        source="ai",
        source_url="https://example.org/huettlingen/martinimarkt",
    ),
    # --- Neighbouring regions ------------------------------------------------------------
    SeedEvent(
        "heidenheimer-schlossfest",
        "Heidenheimer Schlossfest",
        "Schlossfest",
        "stadtfest",
        "heidenheim",
        "published",
        5,
        3,
        "Schloss Hellenstein",
        "Schlosshaustraße 56",
        "Heidenheim an der Brenz",
        "89518",
        48.6767,
        10.1541,
    ),
    SeedEvent(
        "heidenheimer-weihnachtsmarkt",
        "Heidenheimer Weihnachtsmarkt",
        "Weihnachtsmarkt",
        "weihnachtsmarkt",
        "heidenheim",
        "published",
        61,
        23,
        "Eugen-Jaekle-Platz",
        "Eugen-Jaekle-Platz 1",
        "Heidenheim an der Brenz",
        "89518",
        48.6780,
        10.1520,
    ),
    SeedEvent(
        "ulmer-schwoermontag",
        "Ulmer Donaufest",
        "Donaufest",
        "stadtfest",
        "ulm",
        "published",
        -2,
        5,
        "Donauufer",
        "Schwörhausgasse 6",
        "Ulm",
        "89073",
        48.3960,
        9.9900,
    ),
    SeedEvent(
        "ulmer-weihnachtsmarkt",
        "Ulmer Weihnachtsmarkt",
        "Weihnachtsmarkt",
        "weihnachtsmarkt",
        "ulm",
        "published",
        58,
        28,
        "Münsterplatz",
        "Münsterplatz 1",
        "Ulm",
        "89073",
        48.3985,
        9.9918,
    ),
    SeedEvent(
        "ulmer-messe",
        "Ulmer Herbstmesse",
        "Herbstmesse",
        "markt",
        "ulm",
        "published",
        10,
        5,
        "Messe Ulm",
        "Böfinger Straße 50",
        "Ulm",
        "89073",
        48.4167,
        10.0167,
    ),
    SeedEvent(
        "noerdlinger-messe",
        "Nördlinger Mess'",
        "Mess'",
        "volksfest",
        "schwaben",
        "published",
        14,
        10,
        "Kaiserwiese",
        "Kaiserwiese 1",
        "Nördlingen",
        "86720",
        48.8513,
        10.4883,
    ),
    SeedEvent(
        "augsburger-plaerrer",
        "Augsburger Herbstplärrer",
        "Plärrer",
        "volksfest",
        "schwaben",
        "published",
        3,
        14,
        "Plärrergelände",
        "Langemarckstraße 32",
        "Augsburg",
        "86150",
        48.3775,
        10.8850,
    ),
    SeedEvent(
        "augsburger-christkindlesmarkt",
        "Augsburger Christkindlesmarkt",
        "Christkindlesmarkt",
        "weihnachtsmarkt",
        "schwaben",
        "published",
        59,
        27,
        "Rathausplatz",
        "Rathausplatz 2",
        "Augsburg",
        "86150",
        48.3689,
        10.8986,
    ),
    SeedEvent(
        "muenchner-herbstdult",
        "Münchner Herbstdult",
        "Herbstdult",
        "markt",
        "schwaben",
        "published",
        22,
        9,
        "Mariahilfplatz",
        "Mariahilfplatz 1",
        "München",
        "80331",
        48.1290,
        11.5810,
    ),
    SeedEvent(
        "nuernberger-christkindlesmarkt",
        "Nürnberger Christkindlesmarkt",
        "Christkindlesmarkt",
        "weihnachtsmarkt",
        "franken",
        "published",
        57,
        29,
        "Hauptmarkt",
        "Hauptmarkt 1",
        "Nürnberg",
        "90403",
        49.4540,
        11.0775,
    ),
    SeedEvent(
        "dinkelsbuehler-kinderzeche",
        "Dinkelsbühler Herbstfest",
        "Herbstfest",
        "stadtfest",
        "franken",
        "published",
        9,
        4,
        "Altstadt",
        "Weinmarkt 1",
        "Dinkelsbühl",
        "91550",
        49.0700,
        10.3190,
    ),
    SeedEvent(
        "wuerzburger-kiliani",
        "Würzburger Herbstvolksfest",
        "Herbstvolksfest",
        "volksfest",
        "franken",
        "published",
        16,
        10,
        "Talavera",
        "Talavera 1",
        "Würzburg",
        "97070",
        49.7990,
        9.9180,
    ),
    SeedEvent(
        "rothenburger-reichsstadtfest",
        "Rothenburger Altstadtfest",
        "Altstadtfest",
        "stadtfest",
        "franken",
        "cancelled",
        11,
        3,
        "Marktplatz",
        "Marktplatz 1",
        "Rothenburg ob der Tauber",
        "91541",
        49.3771,
        10.1792,
        cancel_reason="Aus organisatorischen Gründen abgesagt.",
    ),
    SeedEvent(
        "stuttgarter-weindorf",
        "Stuttgarter Weindorf",
        "Weindorf",
        "weinfest",
        "stuttgart",
        "published",
        -5,
        12,
        "Marktplatz",
        "Marktplatz 1",
        "Stuttgart",
        "70173",
        48.7758,
        9.1776,
    ),
    SeedEvent(
        "cannstatter-wasen",
        "Herbstfest am Wasen",
        "Wasen",
        "volksfest",
        "stuttgart",
        "published",
        -6,
        17,
        "Cannstatter Wasen",
        "Mercedesstraße 50",
        "Stuttgart",
        "70174",
        48.7930,
        9.2240,
    ),
    SeedEvent(
        "stuttgarter-weihnachtsmarkt",
        "Stuttgarter Weihnachtsmarkt",
        "Weihnachtsmarkt",
        "weihnachtsmarkt",
        "stuttgart",
        "published",
        56,
        30,
        "Schillerplatz",
        "Schillerplatz 1",
        "Stuttgart",
        "70173",
        48.7760,
        9.1790,
    ),
    SeedEvent(
        "goeppinger-maientag",
        "Göppinger Stadtfest",
        "Stadtfest GP",
        "stadtfest",
        "stuttgart",
        "published",
        25,
        3,
        "Marktplatz",
        "Marktstraße 1",
        "Göppingen",
        "73033",
        48.7031,
        9.6526,
    ),
    SeedEvent(
        "heilbronner-herbstmesse",
        "Heilbronner Herbstmesse",
        "Herbstmesse",
        "markt",
        "stuttgart",
        "published",
        7,
        6,
        "Theresienwiese",
        "Theresienstraße 1",
        "Heilbronn",
        "74072",
        49.1500,
        9.2250,
    ),
    SeedEvent(
        "stuttgarter-sommerfest",
        "Stuttgarter Sommerfest",
        "Sommerfest",
        "stadtfest",
        "stuttgart",
        "published",
        -60,
        4,
        "Schlossplatz",
        "Schlossplatz 1",
        "Stuttgart",
        "70173",
        48.7784,
        9.1800,
    ),
)
